apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: preferencedestination
spec:
  match: destination.labels["app"] == "preference"
  actions:
  - handler: preferencewhitelist.listchecker
    instances:
    - sourceservice.listentry