apiVersion: config.istio.io/v1alpha2
kind: listchecker
metadata:
  name: recommendationwhitelist
spec:
  # providerUrl: ordinarily black and white lists are maintained
  # externally and fetched asynchronously using the providerUrl.
  overrides: ["preference"]  # overrides provide a static list
  blacklist: false